version: '3.8'

services:
  # Nacos 服务
  nacos:
    build:
      context: ./nacos2.3.2
      dockerfile: Dockerfile
    container_name: nacos
    ports:
      - "8848:8848"
    environment:
      MODE: standalone
    volumes:
      - nacos_logs:/home/nacos/logs
      - nacos_data:/home/nacos/data
    networks:
      - app-network
    restart: unless-stopped

  # XXL-Job 服务
  xxl-job:
    build:
      context: ./xxl-job
      dockerfile: Dockerfile
    container_name: xxl-job
    ports:
      - "8008:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://host.docker.internal:3306/xxl_job?useSSL=false&serverTimezone=Asia/Shanghai"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      XXL_JOB_ACCESS_TOKEN: "k9ImAW4U9es54VEB"
    networks:
      - app-network
    restart: unless-stopped

  # Nginx 服务
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx_logs:/var/log/nginx
      - ./www:/www
    depends_on:
      - php74
    networks:
      - app-network
    restart: unless-stopped

  # PHP7.4 服务
  php74:
    build:
      context: ./php74
      dockerfile: Dockerfile
    container_name: php74
    ports:
      - "9000:9000"
    volumes:
      - ./www:/www
    networks:
      - app-network
    restart: unless-stopped

  # Node20 服务
  node20:
    build:
      context: ./node20
      dockerfile: Dockerfile
    container_name: node20
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
    volumes:
      - ./node_app:/data
    working_dir: /data
    networks:
      - app-network
    restart: unless-stopped

  # JDK8 服务
  jdk8:
    build:
      context: ./jdk8
      dockerfile: Dockerfile
    container_name: jdk8
    ports:
      - "9003:9003"
    volumes:
      - ./java_app:/usr/data
      - java_logs:/usr/data/logs
    networks:
      - app-network
    restart: unless-stopped

  camoufox:
    build: ./camoufox
    ports:
      - "5345:5345"
    environment:
      # 设置一个你最终Gemini服务的API密钥
      - AUTH_API_KEY=123456
    volumes:
      - ./camoufox/camoufox-py/config.yaml:/app/config.yaml
      - ./camoufox/camoufox-py/cookies:/app/cookies
      - ./camoufox/camoufox-py/logs:/app/logs
    restart: always
    networks:
      - app-network

# 网络配置
networks:
  app-network:
    driver: bridge
  default:
    external:
      name: bridge

# 数据卷配置
volumes:
  nacos_logs:
    driver: local
  nacos_data:
    driver: local
  nginx_logs:
    driver: local
  java_logs:
    driver: local