FROM nacos/nacos-server:v2.3.2

EXPOSE 8848

# ​日志目录​：/home/nacos/logs
# ​配置目录​：/home/nacos/conf
# ​数据目录​：/home/nacos/data

ENV MODE=standalone 

COPY ./application.properties /home/nacos/conf/application.properties