#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running build before commit..."

# 执行构建
npm run rebuild


# 如果构建失败，退出并显示错误
if [ $? -ne 0 ]; then
    echo "Build failed!"
    exit 1
fi

# 添加构建文件到暂存区
git add .